apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-iaca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-iaca
    app.kubernetes.io/part-of: cin4s-839-0035-app
  name: devfile-sample-iaca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-iaca
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-iaca
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0035-tenant/cin4s-839-0035-app/devfile-sample-iaca@sha256:d676544c795b4b90971a01bb8b2146fe2ad40dc98c8c57e837ca7260a2a4bfde
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
